# Generated by Django 3.0.5 on 2020-04-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='biograypy',
            new_name='biography',
        ),
    ]
